### ISSUE TITLE
update dictionary fail

### ISSUE THREAD

**Issue by augustwangact** [MBB200291/SearchACT#24]
C:\Users\augustwang\Desktop\SearchACT-master
# Read file: 20200820行動基因通訊錄含部門.xlsx
Traceback (most recent call last):
  File ".\UpdataContact.py", line 203, in <module>
    main()
  File ".\UpdataContact.py", line 200, in main
    MakeDict(locate_contact_file())# int(sys.argv[2]))
  File ".\UpdataContact.py", line 64, in MakeDict
    contacts, excel_file_name = read_excel(path_contact)
  File ".\UpdataContact.py", line 54, in read_excel
    contacts = remove_blank(pd.read_excel(path_contact))
  File "C:\Users\augustwang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pandas\util\_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\augustwang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pandas\io\excel\_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Users\augustwang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pandas\io\excel\_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "C:\Users\augustwang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pandas\io\excel\_xlrd.py", line 21, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "C:\Users\augustwang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pandas\compat\_optional.py", line 93, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

**Comment by linkuanhang** [comment]
應該要新增 xlrd 進 requirements.txt

**Comment by MBB200291** [comment]
> 應該要新增 xlrd 進 requirements.txt

這個沒在Python內建library中嗎?
